export default {
    'zh-cn': {
        'nights.tilemap.name': '瓦片地图',
        'nights.tilemap.show': '设置[SHOW_MODE]',
        'nights.tilemap.setTileSize': '设置瓦片大小 宽:[W]像素 高:[H]像素',
        'nights.tilemap.setMapSize': '设置地图大小 宽:[W]个瓦片 高:[H]个瓦片',
        'nights.tilemap.setTileView': '设置地图摄像机 x:[X] y:[Y]',
        'nights.tilemap.createTileSet': '创建从图片[TEXTURE]的 坐标:[X][Y] 大小:[W][H] 偏移:[OX][OY] 的瓦片命名为[TILE_ID]',
        'nights.tilemap.deleteTileSet': '删除瓦片集名为[TILE_ID]的瓦片',
        'nights.tilemap.deleteAllTileSet': '删除全部瓦片集',
        'nights.tilemap.getAllTileSet': '所有瓦片集',
        'nights.tilemap.getTile': '获取[LAYER]层的瓦片的[X][Y]的瓦片名称',
        'nights.tilemap.setTile': '设置地图中[LAYER]层的[X][Y]瓦片为[TILE_ID]瓦片',
        'nights.tilemap.clearTile': '擦除地图中[LAYER]层的[X][Y]的瓦片',
        'nights.tilemap.clearAllTile': '擦除[LAYER]层',
        'nights.tilemap.createTileLayer': '创建瓦片层，命名为[LAYER_NAME]',
        'nights.tilemap.deleteTileLayer': '删除瓦片层[LAYER_NAME]',
        'nights.tilemap.getTileLayers': '获取所有瓦片层',
        'nights.tilemap.joinTileMap': '加入[TILEMAP]的瓦片地图',
        'nights.tilemap.setLayerInTileMap': '图层(非原版图层)设为地图中的第[LAYER]层第[ROW]行瓦片',
        'nights.tilemap.quitTilemap': '退出当前地图',
        'nights.tilemap.tileToPos': '地图中第X列第Y行的瓦片的[POSITION]坐标',
        'nights.tilemap.posToTile': '位于x:[X]y:[Y]位置的瓦片是在地图中的第几[POSITION_TILEMAP]？',


        'nights.tilemap.basic': '基础操作',
        'nights.tilemap.tileset': '瓦片集合',
        'nights.tilemap.tile': '瓦片操作',
        'nights.tilemap.tilelayer': '瓦片层',

        'nights.tilemap.layer': '图层管理',
        'nights.tilemap.position': '坐标变换',

        'nights.tilemap.showTilemap': '显示精灵以及瓦片地图',
        'nights.tilemap.hideTilemap': '仅显示精灵',

    },
    en: {
        'nights.tilemap.name': 'Tilemap',
        'nights.tilemap.show': 'Set [SHOW_MODE]',
        'nights.tilemap.setTileSize': 'Set tile size, width: [W] pixels, height: [H] pixels',
        'nights.tilemap.setMapSize': 'Set map size, width: [W] tiles, height: [H] tiles',
        'nights.tilemap.setTileView': 'Set tile camera position, x: [X], y: [Y]',
        'nights.tilemap.createTileSet': 'Create a tile named [TILE_ID] from the picture [TEXTURE] with coordinates [X][Y], size [W][H], and offset [OX][OY].',
        'nights.tilemap.deleteTileSet': 'Delete tile set named [TILE_ID]',
        'nights.tilemap.deleteAllTileSet': 'Delete all tile sets',
        'nights.tilemap.getAllTileSet': 'All tile sets',
        'nights.tilemap.getTile': 'Get the name of the tile at column [X], row [Y] in layer [LAYER]',
        'nights.tilemap.setTile': 'Set tile at column [X], row [Y] in layer [LAYER] to [TILE_ID]',
        'nights.tilemap.clearTile': 'Clear tile at column [X], row [Y] in layer [LAYER]',
        'nights.tilemap.clearAllTile': 'Clear all tiles in layer [LAYER]',
        'nights.tilemap.createTileLayer': 'Create a new tile layer named [LAYER_NAME]',
        'nights.tilemap.deleteTileLayer': 'Delete tile layer named [LAYER_NAME]',
        'nights.tilemap.getTileLayers': 'Get all tile layers',
        'nights.tilemap.joinTileMap': 'Join the tilemap [TILEMAP]',
        'nights.tilemap.setLayerInTileMap': 'Set the non-original layer as the [ROW]th row in the [LAYER]th layer of the map',
        'nights.tilemap.quitTilemap': 'Exit current map',
        'nights.tilemap.tileToPos': 'The tile at column [X], row [Y] in the map has the [POSITION] position.',
        'nights.tilemap.posToTile': 'Which [POSITION_TILEMAP] is the tile located at x:[X] y:[Y] in the map?',

        'nights.tilemap.basic': 'Basic Operations',
        'nights.tilemap.tileset': 'Tilesets',
        'nights.tilemap.tilelayer': 'Tile Layer',
        'nights.tilemap.tile': 'Tile Operations',
        'nights.tilemap.layer': 'Layer Management',
        'nights.tilemap.position': 'Coordinate Transformation',

        'nights.tilemap.showTilemap': 'Show Sprites and Tilemap',
        'nights.tilemap.hideTilemap': 'Show Sprites Only'
    },
}